### ISSUE TITLE
Docker: Re-enable multi-arch build: arm, arm64, amd64, aarch64

### ISSUE THREAD

**Issue by joekhoobyar** [prometheus-community/smartctl_exporter#105]
The last multi-arch build was `v0.7.0`.

Is there any reason not to re-enable it?

**Comment by martivo** [comment]
This seems to be when it got dropped https://github.com/prometheus-community/smartctl_exporter/pull/79 
To work around it:
```
FROM alpine:3
LABEL maintainer="The Prometheus Authors <prometheus-developers@googlegroups.com>"
RUN apk add smartmontools

RUN wget https://github.com/prometheus-community/smartctl_exporter/releases/download/v0.9.1/smartctl_exporter-0.9.1.linux-arm64.tar.gz && tar xvzf smartctl_exporter-0.9.1.linux-arm64.tar.gz && ls -l smartctl_exporter-0.9.1.linux-arm64.tar.gz && mv smartctl_exporter-0.9.1.linux-arm64/smartctl_exporter /bin/smartctl_exporter && rm -rf smartctl_exporter-0.9.1.linux-*

EXPOSE      9633
USER        nobody
ENTRYPOINT  [ "/bin/smartctl_exporter" ]
```

**Comment by frittentheke** [comment]
@joekhoobyar  I suppose this issue is fixed ... recent builds are for all sorts of archs: https://github.com/prometheus-community/smartctl_exporter/releases/tag/v0.10.0

**Comment by NiceGuyIT** [comment]
Yup. arm64 was built in the latest release.

**Comment by jfcoz** [comment]
Hi
arm64 is build in release, but the arm64 docker image is still missing on https://quay.io/repository/prometheuscommunity/smartctl-exporter?tab=tags

**Comment by NiceGuyIT** [comment]
Thanks for catching that @jfcoz. The title and OP doesn't mention Docker. Let's fix that.

**Comment by SuperQ** [comment]
Our standard base container, the busybox container, has a naming convention so we can select which arch output.

For example:
```dockerfile
ARG ARCH="amd64"
ARG OS="linux"
FROM quay.io/prometheus/busybox-${OS}-${ARCH}:latest
```

We use alpine here for the base container so we can get smartmontools installed. I couldn't figure out a way to parameterize the `ARCH` in the alpine `FROM`.

In theory, it should work with `FROM arm64v8/alpine:3`, but I think we would need to run on an ARM worker node for the `apk add` to function.

**Comment by NiceGuyIT** [comment]
Adding the response here to keep the thread.

@jfcoz PR #150 didn't work. The [prometheuscommunity/smartctl-exporter](https://hub.docker.com/r/prometheuscommunity/smartctl-exporter/tags) image shows 2 hashes for `linux/amd64`.
![image](https://github.com/prometheus-community/smartctl_exporter/assets/7763429/5d9b8acb-0cde-43e3-afb4-17405b58a82f)

Meanwhile, [prometheuscommunity/smartctl-exporter-linux-arm64](https://hub.docker.com/r/prometheuscommunity/smartctl-exporter-linux-arm64/tags) has a `linux/amd64` os/arch.
![image](https://github.com/prometheus-community/smartctl_exporter/assets/7763429/23d6f162-5041-45b4-9dd8-dc8b29d5e1ae)

I'm going to revert the changes.

**Comment by stepanbaghdasaryan** [comment]
Unfortunately there is still no arm64 image in the latest or in v0.11.0 version.

https://quay.io/repository/prometheuscommunity/smartctl-exporter/manifest/sha256:aa34799fcc8d278e427a3995bbdc334e7be6508cb8b2d406f38a3a1a2b1b582f

Is it known when this will be fixed?

**Comment by LilDrunkenSmurf** [comment]
Also interested in an ARM image.

**Comment by LilDrunkenSmurf** [comment]
Thanks to @martivo I successfully built an ARM image:
<https://github.com/LilDrunkenSmurf/containers/pkgs/container/smartctl_exporter/167606210?tag=0.11.0>
<https://github.com/LilDrunkenSmurf/containers/blob/main/apps/smartctl_exporter/Dockerfile>

**Comment by stepanbaghdasaryan** [comment]
@NiceGuyIT Are there some known issues or blockers why you still don't activate the support for ARM64 Docker images??

**Comment by dimm0** [comment]
Also interested in re-enabling this

**Comment by NiceGuyIT** [comment]
@stepanbaghdasaryan This issue is to provide a multi-architecture build in [prometheuscommunity/smartctl-exporter][1]. PR #150 did not fix the mutli-arch build and thus was reverted.

However, in hind sight, I see it enabled [prometheuscommunity/smartctl-exporter-linux-arm64][2] which is a different image. I.e. it's not multi-arch. Enabling this build until the mutli-arch is fixed is better than having no build. I'll see about enabling PR #150 or creating another PR.

As for why multi-architecture is not working, see SuperQ's [comment][3].

[1]: https://hub.docker.com/r/prometheuscommunity/smartctl-exporter/tags
[2]: https://hub.docker.com/r/prometheuscommunity/smartctl-exporter-linux-arm64/tags
[3]: https://github.com/prometheus-community/smartctl_exporter/issues/105#issuecomment-1681567204

**Comment by kashalls** [comment]
This can be done with the official `docker/build-push-action` and `docker/setup-buildx-action` available with github actions. I can implement this if someone tells me where it should belong or you can look at how I set this up to build a nodejs package into a container with multi-arch: [github.com/kashalls/border](https://github.com/kashalls/border/blob/74355d46125fef6ec5a9f8713e8e30a22e99bd86/.github/workflows/container-ci.yaml#L64)

**Comment by brettinternet** [comment]
Is there a workaround with this when using the helm chart prometheus-smartctl-exporter?

**Comment by nairol203** [comment]
I would really appreciate an arm version for the docker image

**Comment by NiceGuyIT** [comment]
@SuperQ Can you give me access to the `prometheuscommunity` organization on CircleCI so I can troubleshoot the build process? Any insight into the build process is also appreciated.

**Comment by kashalls** [comment]
@NiceGuyIT At one point, I was just going to PR it so that it builds to GHCR packages. If you want I can still do that.

**Comment by alex-dna-tech** [comment]
My temporary solution is to build a custom container from the released tarball:

__docker-compose.yml__
```yml
services:
  nvme-exporter:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        ARCH: "arm64"
        VERSION: "0.12.0"
    restart: unless-stopped
    privileged: true
```
__Dockerfile__
```dockerfile
FROM alpine AS downloader
ARG ARCH="amd64"
ARG VERSION="0.12.0"

RUN wget -O release.tar.gz https://github.com/prometheus-community/smartctl_exporter/releases
/download/v${VERSION}/smartctl_exporter-${VERSION}.linux-${ARCH}.tar.gz \
    && tar -xzf release.tar.gz__docker-compose.yml__
```yml
services:
  nvme-exporter:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        ARCH: "arm64"
        VERSION: "0.12.0"
    restart: unless-stopped
    privileged: true
```
__Dockerfile__
```dockerfile

FROM alpine:latest
ARG ARCH="amd64"
ARG VERSION="0.12.0"

LABEL maintainer="The Prometheus Authors <prometheus-developers@googlegroups.com>"

RUN apk --no-cache add smartmontools
COPY --from=downloader /smartctl_exporter-${VERSION}.linux-${ARCH}/smartctl_exporter /bin/sma
rtctl_exporter

EXPOSE      9633
USER        nobody
ENTRYPOINT  [ "/bin/smartctl_exporter" ]
```

**Comment by joryirving** [comment]
Hilariously, the image I rolled has seen a ton of usage: https://github.com/joryirving/containers/pkgs/container/smartctl_exporter

**Comment by Serverfrog** [comment]
Then i will just use your helmrelease.yaml a bit modified on my RK1 Cluster with 6 SATA Port NVMe Adapters, before somebody comes up of the idea that ARM64 Architectures wont have much to do with HDD's or need smartctl...

**Comment by kfox1111** [comment]
@joryirving Tried to launch the chart on a pi cluster. failed to find the image. Tweaked the settings to point at your image. Worked perfectly. Thanks! :)

**Comment by mossad-zika** [comment]
please add official arm image

**Comment by joryirving** [comment]
If anyone is interesting, I also PR'd this to the `home-operations` org: https://github.com/home-operations/containers/pkgs/container/smartctl-exporter

**Comment by adrianrosu54** [comment]
Is there still no official ARM64 image?

**Comment by kashalls** [comment]
> Is there still no official ARM64 image?

No, there is no official ARM64-supported images. There hasn't been any interest from the maintainers to add support for this.

As a work around, the [ghcr.io/home-operations/smartctl-exporter](https://github.com/home-operations/containers/pkgs/container/smartctl-exporter) is as close as we will get.

**Comment by dnesting** [comment]
Digging into this, PR #150 works correctly for me. I suspect the original attempt ran using a Docker engine before buildkit was the default. Without buildkit, --platform is ignored.  I recommend just trying the same change again.

```sh
for bk in 0 1; do
  for arch in amd64 arm64; do
    DOCKER_BUILDKIT=$bk docker build -q --build-arg ARCH=$arch --build-arg OS=linux -t repro:$bk-$arch .
    echo repro:$bk-$arch got $(docker image inspect repro:$bk-$arch --format '{{.Architecture}}')
  done
done
```

```
repro:0-amd64 got arm64
repro:0-arm64 got arm64
repro:1-amd64 got amd64
repro:1-arm64 got arm64
```

Without buildkit, it picks up the architecture of the host (in my case arm64 but in your CI it was probably amd64).

So when I cherry-pick #150 and run it myself today, I get lovely multi-arch images:

```
docker buildx imagetools inspect ghcr.io/dnesting/smartctl-exporter:ci-pr150-test
Name:      ghcr.io/dnesting/smartctl-exporter:ci-pr150-test
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:4e73cc87ab69f663a1cff043a7463199fca677b36800f90d07bceb08e35ac292

Manifests:
  Name:      ghcr.io/dnesting/smartctl-exporter:ci-pr150-test@sha256:18cb1a2e4e858f50035fc3cdcbcdd0ba6ca13ba77d9242ac96eb3cfa27c284b3
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64

  Name:      ghcr.io/dnesting/smartctl-exporter:ci-pr150-test@sha256:02d9796a304359be4fb22d2e908d8a6d0a91b938cdee2158d91868a92050250c
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm64
```

I tested these images on my own amd64 and arm64 nodes and it correctly pulled the right ones and the binaries ran without an issue.

```
for p in amd64 arm64; do
  c=$(docker create --platform linux/$p ghcr.io/dnesting/smartctl-exporter:ci-pr150-test)
  docker cp -q "$c:/bin/smartctl_exporter" "/tmp/exporter-$p"
  docker cp -q "$c:/usr/sbin/smartctl" "/tmp/smartctl-$p"
  docker rm -q "$c" >/dev/null
  file /tmp/exporter-$p /tmp/smartctl-$p
done

ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=MljukdizScE3SC0esA46/dJBGpVDYhxDQXKlXbK3L/79a6p16Lal2itY83Y_n2/HO9BjxWb5f372aVAgxmT, BuildID[sha1]=5ec3266204b6b6d697af3158200dafedaf8bed51, with debug_info, not stripped
ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, BuildID[sha1]=b4b2c64feca8057e4d2bca2ba48248ebebc5f1fc, stripped

ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=YPRKkeE3C-XzNR2wCQsi/aTDE6q_9euu--A6O4tUm/-hMT0QPYHR0vIICH5uN4/b8kqv8lSuZ16j7w_UQWC, BuildID[sha1]=8c090ead058deb6c0ace5c25b795c66b4319f361, with debug_info, not stripped
ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-aarch64.so.1, BuildID[sha1]=ec7675a322586ccaa54e0af5394e46eae53b089d, stripped
```

See also the ipmi_exporter which has exactly the same pattern this repo does (adding a package in the Dockerfile). Their multi-arch change happened after Buildkit was enabled by default, so they didn't hit the same problem.

https://github.com/prometheus-community/ipmi_exporter/blob/master/Dockerfile
